jobs:
  - title: Public Relations Office, North South University
    company: Official Photographer & PR Content Producer
    period: "2024 - Present"
    description: >
      As the Official Photographer and PR Content Producer for NSU Digital, the official page of North South
      University, I specialize in capturing, producing, and curating high-quality photo and video content from
      various campus events. I handle media monitoring and work closely with journalists to ensure timely
      coverage and accurate representation of the university’s activities across digital and traditional platforms.
      Through this role, I have gained practical experience in photojournalism and contributed visual content for
      news portals, covering meetings, corporate shoots, workshops, and special occasions to maintain and
      promote a strong, professional image for the university’s community and audience.

  - title: Snapshot Stories
    company: Founder & Head of Operations
    period: "2024 - Present"
    description: >
      Snapshot Production and Snapshot Stories are professional photography and cinematography brands specializing in corporate shoots, fashion, branding, weddings, concerts, and events. As the Founder, Head of Operations and Chief Photographer, I lead creative direction, manage client projects, and provide direction to teams to ensure smooth production workflows. I deliver high-quality visual storytelling for brands and individuals, making sure every project captures unique stories with professional standards.
    projects:
      - title: Behance portfolio
        description: Click here to visit.
        href: "https://www.behance.net/tamzidnavid"
        image: "Behance.JPG"

      - title: NSU ACM SC Logo Animation
        description: Behind the scenes of visual storytelling
        href: "https://www.youtube.com/watch?v=Cx_Jd5rVOIY"
        image:

      - title: Rafsan Sabab -Getting nostalgic on a “Marvel” ous show
        description: Reels -Showcasing diverse creative work
        href: "https://www.facebook.com/reel/3016668995346732"
        image: "fb5.jpg"

      - title: Roman Sacrifice - NIDRA (Official Music Video)
        description: Official Music Video
        href: "https://www.youtube.com/watch?v=rl2RBzhgSsc"
        image: 
      - title: নর্থ সাউথ ইউনিভার্সিটিতে বাংলা নববর্ষ ১৪৩৩ উদযাপন
        description: Public Relations Office (NSU Digital)
        href: "https://www.facebook.com/reel/1495923098853899"
        image: "ss.jpg"

      - title: NSU ACM Student Chapter
        description: Promo Video -Stories from the creative process
        href: "https://www.facebook.com/reel/696975402946928"
        image: "fb2.jpg"

      - title: 𝗖𝗼𝗮𝘀𝘁𝗮𝗹 𝗨𝗹𝘁𝗿𝗮 𝗕𝗮𝗻𝗴𝗹𝗮𝗱𝗲𝘀𝗵
        description: Event Trailer -Dhaka Stadium Run 2025
        href: "https://www.facebook.com/reel/876722401486961"
        image: "Coastal.jpg"

  - title: NSU ACM Student Chapter
    company: Founding Coordinator & Sub-Executive
    period: "2024 - 2026"
    description: >
      As the Founding Coordinator of the Media & Documentation and Sub-Executive of Team Promotions at NSU
      ACM Student Chapter, I led initiatives in public relations, event documentation, and promotional content
      creation. I played a key role in building the group from the ground up, coordinated media coverage,
      sponsorship materials, and press releases to enhance the chapter's visibility. I progressed from probationary
      member to leadership roles, and developed strong leadership, teamwork, and communication skills within a
      dynamic student community.
    
  - title: English Olympiad
    company: Campus Ambassador & Organizer
    period: "2023 - 2025"
    description: >
      As an Organizer & Campus Ambassador, I played a pivotal role in the committee dedicated to the growth and
      success of the English Olympiad. Through effective coordination, engagement, and event organization, I
      contributed to its overall success and positive impact on campus. Additionally, I organized the event and
      served as an adjudicator for the final round of Season 3.
    
  - title: National STEAM Olympiad
    company: Campus Ambassador
    period: "2023 - 2025"
    description: >
      Working as a Campus Ambassador for the National STEAM Olympiad, I represented the organization at my
      university, promoted and organized events related to science, technology, engineering, arts, and
      mathematics. I effectively communicated program details, engaged students, and helped facilitate a
      meaningful educational experience for participants. It was a great success for me, and I was honored to be
      selected as one of the top 30 nominee ambassadors among 1,300 others nationwide.
    
